---
sidebar: sidebar 
permalink: install-setup/deploy-hardware.html 
keywords: asa r2, install hardware, deploy hardware, aff a1k, aff a70, aff a90, aff c80, asa a1k, asa a90, asa a70 
summary: Descubra cómo instalar los kits de guías para el sistema de almacenamiento y las bandejas de almacenamiento R2 de ASA, y cómo proteger el hardware de ASA R2 en el armario o el rack de telecomunicaciones. 
---
= Instale su sistema de almacenamiento R2 de ASA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de preparar la instalación del sistema de almacenamiento ASA R2, instale el hardware para el sistema. En primer lugar, instale los kits de guías. A continuación, instale y proteja su sistema de almacenamiento en un armario o rack de telecomunicaciones.

.Antes de empezar
* Asegúrese de tener las instrucciones incluidas en el kit de guías.
* Tenga en cuenta los problemas de seguridad asociados con el peso del sistema de almacenamiento y la bandeja de almacenamiento.
* Comprenda que el flujo de aire a través del sistema de almacenamiento entra desde la parte frontal donde se instalan las tapas de la cubierta protectora o de los extremos y sale de la parte posterior donde se encuentran los puertos.


.Pasos
. Instale los kits de rieles para el sistema de almacenamiento y las bandejas de almacenamiento, según sea necesario, siguiendo las instrucciones incluidas en los kits.
. Instale y proteja su sistema de almacenamiento en el armario o el rack de telecomunicaciones:
+
.. Coloque el sistema de almacenamiento en los rieles situados en el centro del armario o rack de telecomunicaciones, y luego apoye el sistema de almacenamiento desde la parte inferior y deslícelo en su lugar.
.. Fije el sistema de almacenamiento al armario o al rack de telecomunicaciones con los tornillos de montaje incluidos.


. Instale la bandeja de almacenamiento:
+
.. Coloque la parte posterior de la bandeja de almacenamiento en los raíles, apoye la bandeja desde la parte inferior y deslícela en el armario o el rack de telecomunicaciones.
+
Si va a instalar varias bandejas de almacenamiento, coloque la primera bandeja de almacenamiento directamente encima de las controladoras. Coloque la segunda bandeja de almacenamiento directamente debajo de las controladoras. Repita este patrón para todas las bandejas de almacenamiento adicionales.

.. Fije la bandeja de almacenamiento al armario o al rack Telco con los tornillos de montaje incluidos.


. Conecte los dispositivos de gestión de cables a la parte posterior del sistema de almacenamiento.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[Instale el dispositivo de gestión de cables]

. Conecte el panel frontal a la parte frontal del sistema de almacenamiento.


.El futuro
Después de instalar el hardware de su sistema ASA R2, ustedlink:cable-hardware.html["Conecte los cables de las controladoras y las bandejas de almacenamiento para el sistema ASA R2"].
