---
sidebar: sidebar 
permalink: install-setup/install-setup-requirements.html 
keywords: asa r2, install, setup, requirements, cautions 
summary: Revise el equipo necesario y las precauciones de elevación para el sistema de almacenamiento R2 de ASA y las bandejas de almacenamiento. 
---
= Requisitos de instalación para los sistemas de almacenamiento ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revise el equipo necesario y las precauciones de elevación para el sistema de almacenamiento R2 de ASA y las bandejas de almacenamiento.



== Equipo necesario para la instalación

Para instalar el sistema de almacenamiento R2 de ASA, necesita los siguientes equipos y herramientas.

* Acceso a un explorador web para configurar el sistema de almacenamiento
* Correa de descarga electrostática (ESD)
* Linterna
* Portátil o consola con conexión USB/serie
* Clip de papel o bolígrafo con punta estrecha para ajustar los identificadores de los estantes de almacenamiento
* Destornillador Phillips número 2




== Precauciones de elevación

Los sistemas de almacenamiento y las bandejas de almacenamiento R2 de ASA son pesados. Tenga cuidado al levantar y mover estos elementos.



=== Pesos del sistema de almacenamiento

Tome las precauciones necesarias al mover o levantar su sistema de almacenamiento ASA R2.

[role="tabbed-block"]
====
.A1K
--
Un sistema de almacenamiento ASA A1K puede pesar hasta 28,5 kg (62,83 lbs). Para levantar el sistema de almacenamiento, se necesitan dos personas o un elevador hidráulico.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[ASA A1K Icono de precaución de elevación]

--
.A70 y A90
--
Un sistema de almacenamiento ASA A70 o ASA A90 puede pesar hasta 68,8 kg (151,68 libras). Para levantar el sistema de almacenamiento, utilice cuatro personas o un elevador hidráulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[ASA A90]

--
.A20, A30 Y A50
--
Un sistema de almacenamiento ASA A20, ASA A30 o ASA A50 puede pesar hasta 27,9 kg (61,5 libras). Para levantar el sistema de almacenamiento, se necesitan dos personas o un elevador hidráulico.

image::../media/drw_g_lifting_weight_ieops-1831.svg[ASA A20,A30,or an A50 weight caution icon]

--
====


=== Pesos de los estantes de almacenamiento

Tome las precauciones necesarias al mover o levantar su estante.

[role="tabbed-block"]
====
.Bandeja NS224
--
Un estante NS224 puede pesar hasta 66,78 lbs (30,29 kg). Para levantar el estante, utilice dos personas o un elevador hidráulico. Mantenga todos los componentes en la bandeja (tanto delantera como trasera) para evitar desequilibrar el peso de la bandeja.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 Cuidado de elevación]

--
.Bandeja NS224 con módulos de NSM100B TB
--
Un estante NS224 con NSM100B módulos puede pesar hasta 56,8 lbs (25,8 kg). Para levantar el estante, utilice dos personas o un elevador hidráulico. Mantenga todos los componentes en la bandeja (tanto delantera como trasera) para evitar desequilibrar el peso de la bandeja.

image::../media/drw_ns224_nsm100b_lifting_weight_ieops-1832.svg[NS224 con NSM100b precaución de elevación]

--
====
.Información relacionada
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Información sobre seguridad y avisos normativos"^]


.El futuro
Después de haber revisado los requisitos de hardware, usted link:prepare-hardware.html["Prepare la instalación del sistema de almacenamiento R2 de ASA"].
