---
sidebar: sidebar 
permalink: install-setup/install-setup-requirements.html 
keywords: asa r2, install, setup, requirements, cautions 
summary: Revise el equipo necesario y las precauciones de elevación para el sistema de almacenamiento R2 de ASA y las bandejas de almacenamiento. 
---
= Requisitos de instalación para los sistemas de almacenamiento ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Revise el equipo necesario y las precauciones de elevación para el sistema de almacenamiento R2 de ASA y las bandejas de almacenamiento.



== Equipo necesario para la instalación

Para instalar el sistema de almacenamiento R2 de ASA, necesita los siguientes equipos y herramientas.

* Acceso a un explorador web para configurar el sistema de almacenamiento
* Correa de descarga electrostática (ESD)
* Linterna
* Portátil o consola con conexión USB/serie
* Clip de papel o bolígrafo con punta estrecha para fijar NS224 ID de estante de almacenamiento
* Destornillador Phillips número 2




== Precauciones de elevación

Los sistemas de almacenamiento R2 y las bandejas de almacenamiento NS224 de ASA son pesados. Tenga cuidado al levantar y mover estos elementos.



=== Pesos del sistema de almacenamiento

Tome las precauciones necesarias al mover o levantar su sistema de almacenamiento ASA R2.

[role="tabbed-block"]
====
.ASA A1K
--
Un sistema de almacenamiento ASA A1K puede pesar hasta 28,5 kg (62,83 lbs). Para levantar el sistema, se necesitan dos personas o un elevador hidráulico.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K Icono de precaución de elevación]

--
.ASA A70 y ASA A90
--
Un sistema de almacenamiento A70 de ASA o un sistema de almacenamiento A90 de ASA pueden pesar hasta 68,8 kg (151,68 libras). Para levantar el sistema, se necesitan cuatro personas o un elevador hidráulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90]

--
====


=== Peso del estante de almacenamiento

Un estante de almacenamiento NS224 puede pesar hasta 66,78 lbs (30,29 kg). Para levantar el estante de almacenamiento, se necesitan dos personas o un elevador hidráulico. Conserve todos los componentes en la bandeja de almacenamiento (tanto delantera como trasera) para evitar que se desequilibre el peso de bandeja.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 Cuidado de elevación]

.Información relacionada
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Información sobre seguridad y avisos normativos"^]


.El futuro
Después de haber revisado los requisitos de hardware, usted link:prepare-hardware.html["Prepare la instalación del sistema de almacenamiento R2 de ASA"].
