---
sidebar: sidebar 
permalink: install-setup/set-up-data-access.html 
keywords:  
summary:  
---
= Habilite el acceso a datos desde hosts SAN a su sistema de almacenamiento ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para configurar el acceso a los datos, debe asegurarse de que los parámetros críticos y los ajustes del cliente SAN para un funcionamiento adecuado con ONTAP se hayan configurado correctamente. Si proporciona almacenamiento para su entorno VMware, debe instalar OTV 10,3 solo para la gestión de su almacenamiento ASA R2.



== Configure el acceso a datos desde hosts SAN

La configuración necesaria para configurar el acceso a los datos al sistema ASA R2 desde los hosts SAN varía en función del sistema operativo del host y del protocolo. La configuración correcta es importante para obtener el mejor rendimiento y una correcta recuperación tras fallos.

Consulte la documentación del host SAN de ONTAP para link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["Clientes SCSI VMware vSphere"^] link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Clientes NVMe VMware vSphere"^]y link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html["Otros clientes SAN"^] para configurar correctamente los hosts para conectarse al sistema ASA R2.



== Migrar los equipos virtuales de VMware

Si necesita migrar la carga de trabajo de sus máquinas virtuales desde un sistema de almacenamiento de ASA a un sistema de almacenamiento R2 de ASA, NetApp recomienda utilizar link:https://www.vmware.com/products/cloud-infrastructure/vsphere/vmotion["VSphere vMotion de VMware"^] para realizar una migración activa y sin interrupciones de los datos.



== Migrar datos desde un sistema de almacenamiento de terceros

A partir de ONTAP 9.17.1, puede usar la Importación de LUN Externa (FLI) para migrar datos desde un LUN en un sistema de almacenamiento externo a un sistema ASA r2. Usar FLI para la migración de datos puede ayudarle a mitigar el riesgo de pérdida de datos y tiempo de inactividad durante el proceso.

FLI admite migraciones en línea y fuera de línea. En una migración en línea, el sistema cliente permanece en línea mientras se copian los datos del sistema de almacenamiento externo al sistema de almacenamiento ONTAP . Las migraciones en línea son compatibles con los sistemas operativos Windows, Linux y ESXi. En una migración fuera de línea, el sistema cliente se desconecta, los datos del LUN se copian del sistema de almacenamiento externo al sistema de almacenamiento ONTAP y, a continuación, el sistema cliente vuelve a estar en línea.

* Aprenda a realizar una link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_offline_workflow.html["Migración sin conexión de FLI"^] .
* Aprenda a realizar una link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_online_workflow.html["Migraciones en línea de FLI"^] .




== Configure su sistema R2 de ASA como proveedor de almacenamiento en su entorno VMware

Puede utilizar las herramientas de ONTAP para VMware para habilitar fácilmente su sistema ASA R2 como proveedor de almacenamiento en su entorno VMware.

Las herramientas de ONTAP para VMware vSphere son un conjunto de herramientas que funcionan junto con VMware vCenter Server Virtual Appliance (vcsa) para facilitar la gestión de máquinas virtuales en hosts VMware ESXi.

Los sistemas ASA R2 son compatibles con link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html["Herramientas de ONTAP para VMware vSphere 10,3"^]y versiones posteriores.

Aprenda a link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["Ponga en marcha herramientas de ONTAP para VMware"^]usarlo y luego para hacer lo siguiente:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Añada instancias de vCenter Server"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-esx-server-multipath-and-timeout-settings.html["Configure los ajustes del host ESXi"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/discover-storage-systems-and-hosts.html["Descubra su sistema de almacenamiento R2 y los hosts de ASA"^]


.El futuro
Está preparado para link:../manage-data/provision-san-storage.html["aprovisionar almacenamiento"]habilitar los hosts SAN para leer y escribir datos en unidades de almacenamiento.
