---
sidebar: sidebar 
permalink: secure-data/iscsi-nvme-tcp-connections.html 
keywords: asa r2, secure data, data security, encrypt, data at rest, data-at-rest, encryption, iscsi, nvme/tcp, ipsec, data-in-flight, ip security, secure connections, secure data connections, hardware offload 
summary: 'Si utiliza el protocolo IP en su sistema ASA R2, puede configurar la seguridad IP (IPsec) para mejorar la seguridad de sus datos.' 
---
= Proteja las conexiones IP en sus sistemas de almacenamiento ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si utiliza el protocolo IP en su sistema ASA R2, puede configurar la seguridad IP (IPsec) para mejorar la seguridad de sus datos. IPSec es un estándar de Internet que proporciona cifrado de datos en tránsito, autenticación para el tráfico que fluye entre los puntos finales de red a nivel de IP y protección contra ataques de reinyección y de intermediario malintencionados contra sus datos.

Para los sistemas ASA R2, IPsec está disponible para hosts iSCSI y NVMe/TCP.

En ciertos sistemas ASA R2, varias de las operaciones criptográficas, como el cifrado y las comprobaciones de integridad, pueden descargarse a una tarjeta de controladora de interfaz de red (NIC) compatible. El rendimiento de las operaciones descargadas en la tarjeta NIC es aproximadamente del 5% o menos. Esto puede mejorar significativamente el rendimiento y el rendimiento del tráfico de red protegido por IPsec.

A partir de ONTAP 9.18.1, la descarga de hardware de IPsec compatible se extiende al tráfico IPv6.

Las siguientes tarjetas NIC son compatibles con la descarga de hardware en los siguientes sistemas ASA r2 y versiones de ONTAP :

[cols="3"]
|===
| Tarjeta NIC compatible | Sistemas ASA r2 | Versión ONTAP 


 a| 
X50135A (controlador Ethernet 2p, 40G/100G)
 a| 
* ASA A1K
* ASA A90
* ASA A70

 a| 
ONTAP 9.17.1 y posteriores



 a| 
X60135A (controlador Ethernet 2p, 40G/100G)
 a| 
* ASA A50
* ASA A30
* ASA A20

 a| 
ONTAP 9.17.1 y posteriores



 a| 
X50131A - (controlador Ethernet 2P, 40G/100g/200g/400G)
 a| 
* ASA A1K
* ASA A90
* ASA A70

 a| 
ONTAP 9.16.1 y posteriores



 a| 
X60132A - (controlador Ethernet 4p, 10G/25G)
 a| 
* ASA A50
* ASA A30
* ASA A20

 a| 
ONTAP 9.16.1 y posteriores

|===
Ver ellink:https://hwu.netapp.com/["NetApp Hardware Universe"^] Para obtener más información sobre los sistemas y tarjetas compatibles.

.El futuro
IPsec se configura en su sistema ASA r2 de la misma manera que en otros sistemas ONTAP . Para obtener más información, consulte link:https://docs.netapp.com/us-en/ontap/networking/ipsec-prepare.html["Prepárese para configurar la seguridad IP para la red ONTAP."^].
