---
sidebar: sidebar 
permalink: secure-data/migrate-encryption-keys-between-key-managers.html 
keywords: onboard key manager, external key manager, configure, migrate keys, store keys, authentication keys, encryption keys, asa r2 
summary: 'Puede usar el gestor de claves incorporado de ONTAP en el sistema ASA R2 o un gestor de claves externo o ambos (en un caso) para gestionar las claves de cifrado de datos.' 
---
= Migre las claves de cifrado de datos de ONTAP entre gestores de claves de su sistema ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede gestionar las claves de cifrado de datos mediante el administrador de claves incorporado de ONTAP en el sistema ASA R2 o un gestor de claves externo (o ambos). Solo es posible habilitar los administradores de claves externos en el nivel de máquina virtual de almacenamiento. En el nivel de clúster de ONTAP, es posible habilitar el gestor de claves incorporado o un gestor de claves externo.

[cols="2,2"]
|===
| Si habilita su gestor de claves en... | Puede usar... 


| Solo a nivel de cluster  a| 
Puede usar el gestor de claves incorporado o un gestor de claves externo



| Solo a nivel de máquina virtual de almacenamiento | Solo un gestor de claves externo 


 a| 
Tanto el clúster como el nivel de la máquina virtual de almacenamiento
 a| 
Una de las siguientes combinaciones de gestor de claves:

* Opción 1
+
Nivel de clúster: Gestor de claves incorporado

+
Nivel de máquina virtual de almacenamiento: Administrador de claves externo

* Opción 2
+
Nivel de clúster: Gestor de claves externo

+
Nivel de máquina virtual de almacenamiento: Administrador de claves externo



|===


== Migre claves entre gestores de claves en el nivel del clúster de ONTAP

A partir de ONTAP 9.16.1, puede utilizar la interfaz de línea de comandos (CLI) de ONTAP para migrar claves entre gestores de claves en el nivel del clúster.

[role="tabbed-block"]
====
.De a bordo a externo
--
.Pasos
. Configure el nivel de privilegio en Advanced:
+
[source, cli]
----
set -privilege advanced
----
. Cree una configuración del gestor de claves externo inactivo:
+
[source, cli]
----
security key-manager external create-config
----
. Cambie al gestor de claves externo:
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type KMIP
----
. Elimine la configuración del gestor de claves incorporado:
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type OKM
----
. Configure el nivel de privilegio en admin:
+
[source, cli]
----
set -privilege admin
----


--
.De externo a incorporado
--
.Pasos
. Configure el nivel de privilegio en Advanced:
+
[source, cli]
----
set -privilege advanced
----
. Cree una configuración de gestor de claves incorporada inactiva:
+
[source, cli]
----
security key-manager onboard create-config
----
. Habilite la configuración del gestor de claves incorporado:
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type OKM
----
. Elimine la configuración del gestor de claves externo
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type KMIP
----
. Configure el nivel de privilegio en admin:
+
[source, cli]
----
set -privilege admin
----


--
====


== Migrar claves entre los administradores de claves en todo el clúster de ONTAP y los niveles de máquina virtual de almacenamiento

Puede usar la interfaz de línea de comandos (CLI) de ONTAP para migrar claves entre el administrador de claves en el nivel del clúster y un administrador de claves en el nivel de máquina virtual de almacenamiento.

.Pasos
. Configure el nivel de privilegio en Advanced:
+
[source, cli]
----
set -privilege advanced
----
. Migrar las claves:
+
[source, cli]
----
security key-manager key migrate -from-vserver <storage_vm_name> -to-vserver <storage_vm_name>
----
. Configure el nivel de privilegio en admin:
+
[source, cli]
----
set -privilege admin
----

