---
sidebar: sidebar 
permalink: secure-data/migrate-encryption-keys-between-key-managers.html 
keywords: onboard key manager, external key manager, configure, migrate keys, store keys, authentication keys, encryption keys, asa r2 
summary: 'Puede usar el gestor de claves incorporado de ONTAP en el sistema ASA R2 o un gestor de claves externo o ambos (en un caso) para gestionar las claves de cifrado de datos.' 
---
= Migrar claves de cifrado de datos de ONTAP entre gestores de claves en sistemas ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes gestionar las claves de cifrado de datos con el gestor de claves integrado de ONTAP en tu sistema ASA r2, un gestor de claves externo o ambos en las configuraciones compatibles. Los gestores de claves externos solo son compatibles a nivel de máquina virtual de almacenamiento. A nivel de clúster de ONTAP, puedes usar el gestor de claves integrado o un gestor de claves externo.

[cols="2,2"]
|===
| Si habilita su gestor de claves en... | Puede usar... 


| Solo a nivel de cluster  a| 
Puede usar el gestor de claves incorporado o un gestor de claves externo



| Solo a nivel de máquina virtual de almacenamiento | Solo un gestor de claves externo 


 a| 
Tanto el clúster como el nivel de la máquina virtual de almacenamiento
 a| 
Una de las siguientes combinaciones de gestor de claves:

* Opción 1
+
Nivel de clúster: Gestor de claves incorporado

+
Nivel de máquina virtual de almacenamiento: Administrador de claves externo

* Opción 2
+
Nivel de clúster: Gestor de claves externo

+
Nivel de máquina virtual de almacenamiento: Administrador de claves externo



|===


[[migrate-keys-between-key-managers-at-the-ontap-cluster-level]]
== Migre claves entre gestores de claves en el nivel del clúster de ONTAP

A partir de ONTAP 9.16.1, puedes utilizar la interfaz de línea de comandos (CLI) de ONTAP para migrar claves entre gestores de claves a nivel de clúster.

[role="tabbed-block"]
====
.Del gestor de claves integrado al gestor de claves externo
--
.Pasos
. Configure el nivel de privilegio en Advanced:
+
[source, cli]
----
set -privilege advanced
----
. Cree una configuración del gestor de claves externo inactivo:
+
[source, cli]
----
security key-manager external create-config
----
. Cambie al gestor de claves externo:
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type KMIP
----
. Elimine la configuración del gestor de claves incorporado:
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type OKM
----
. Configure el nivel de privilegio en admin:
+
[source, cli]
----
set -privilege admin
----


--
.Del gestor de claves externo al gestor de claves integrado
--
.Pasos
. Configure el nivel de privilegio en Advanced:
+
[source, cli]
----
set -privilege advanced
----
. Cree una configuración de gestor de claves incorporada inactiva:
+
[source, cli]
----
security key-manager onboard create-config
----
. Habilite la configuración del gestor de claves incorporado:
+
[source, cli]
----
security key-manager keystore enable -vserver <storage_vm_name> -type OKM
----
. Eliminar la configuración del gestor de claves externo
+
[source, cli]
----
security key-manager keystore delete-config -vserver <storage_vm_name> -type KMIP
----
. Configure el nivel de privilegio en admin:
+
[source, cli]
----
set -privilege admin
----


--
====


[[migrate-keys-between-key-managers-across-ontap-cluster-and-storage-vm-levels]]
== Migrar claves entre los administradores de claves en todo el clúster de ONTAP y los niveles de máquina virtual de almacenamiento

Puedes usar la interfaz de línea de comandos (CLI) de ONTAP para migrar claves entre gestores de claves a nivel de clúster y de máquina virtual de almacenamiento.

.Pasos
. Configure el nivel de privilegio en Advanced:
+
[source, cli]
----
set -privilege advanced
----
. Migrar las claves:
+
[source, cli]
----
security key-manager key migrate -from-vserver <storage_vm_name> -to-vserver <storage_vm_name>
----
. Configure el nivel de privilegio en admin:
+
[source, cli]
----
set -privilege admin
----

