---
sidebar: sidebar 
permalink: secure-data/modify-arp-snapshot-retention-period.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: Aprenda a modificar los períodos de retención de instantáneas de ARP para adaptarlos a sus requisitos comerciales y de almacenamiento. 
---
= Modificar los períodos de retención de instantáneas de ARP/AI en los sistemas de almacenamiento ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la Protección Autónoma contra el Ransomware con Inteligencia Artificial (ARP/AI) detecta actividad anómala en una o varias unidades de almacenamiento de tu sistema ASA r2, crea automáticamente una instantánea ARP para proteger los datos. Dependiendo de tu capacidad de almacenamiento y de los requisitos del negocio, podrías querer aumentar o reducir el periodo de retención predeterminado de las instantáneas ARP. Por ejemplo, podrías aumentar el periodo de retención para aplicaciones críticas para el negocio para permitir ventanas de recuperación de datos más largas, o reducirlo para aplicaciones no críticas y así ahorrar espacio de almacenamiento.

El período de retención predeterminado para la instantánea de ARP varía según la acción que realice en respuesta a la actividad anormal.

[cols="2,2"]
|===
| Si realiza esta acción... | Las instantáneas ARP se conservan de forma predeterminada durante... 


| Marcar como falso positivo | 12 horas 


| Marcar como posible ataque de ransomware | 7 días 


| No tome medidas inmediatas | 10 días 
|===
Puedes modificar los períodos de retención predeterminados usando la interfaz de línea de comandos (CLI) de ONTAP. Consulta https://docs.netapp.com/us-en/ontap/anti-ransomware/modify-automatic-snapshot-options-task.html["Modificar las opciones para las instantáneas automáticas de ONTAP"] para ver los pasos para cambiar el período de retención predeterminado.
