---
sidebar: sidebar 
permalink: secure-data/modify-arp-snapshot-retention-period.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, arp/ai, alerts, respond, warnings, security 
summary: Aprenda a modificar los períodos de retención de instantáneas de ARP para adaptarlos a sus requisitos comerciales y de almacenamiento. 
---
= Modificar los períodos de retención de instantáneas de ARP/AI en los sistemas de almacenamiento ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la Protección Autónoma contra Ransomware con Inteligencia Artificial (ARP/IA) detecta actividad anormal en una o más unidades de almacenamiento de su sistema ASA r2, crea automáticamente una instantánea de ARP para proteger los datos de la unidad. Según su capacidad de almacenamiento y las necesidades de su negocio, podría querer aumentar o reducir el periodo de retención predeterminado de las instantáneas de ARP. Por ejemplo, podría querer aumentar el periodo de retención de las aplicaciones críticas para la empresa para, si es necesario, disponer de periodos de retención más largos para la recuperación de datos, o bien, podría querer reducir el periodo de retención de las aplicaciones no críticas para ahorrar espacio de almacenamiento.

El período de retención predeterminado para la instantánea de ARP varía según la acción que realice en respuesta a la actividad anormal.

[cols="2,2"]
|===
| Si realiza esta acción... | Las instantáneas ARP se conservan de forma predeterminada durante... 


| Marcar como falso positivo | 12 horas 


| Marcar como posible ataque de ransomware | 7 días 


| No tome medidas inmediatas | 10 días 
|===
Los períodos de retención predeterminados se pueden modificar mediante la interfaz de línea de comandos (CLI) de ONTAP . Consulte  https://docs.netapp.com/us-en/ontap/anti-ransomware/modify-automatic-snapshot-options-task.html["Modificar las opciones para las instantáneas automáticas de ONTAP"] para conocer los pasos para cambiar el período de retención predeterminado.
