---
sidebar: sidebar 
permalink: secure-data/pause-resume-anti-ransomware-protection.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, pause, resume, suspend 
summary: Si estás planificando un evento de carga de trabajo inusual, puedes suspender temporalmente ARP con análisis de IA para evitar detecciones positivas falsas de ataques de ransomware 
---
= Pausar o reanudar la protección ARP/AI en los sistemas de almacenamiento ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP 9.17.1, puedes utilizar la Protección Autónoma contra el Ransomware con Inteligencia Artificial (ARP/AI) para proteger los datos de tu sistema ASA r2. Si tienes previsto un evento con una carga de trabajo inusual, puedes suspender temporalmente el análisis de ARP/AI para evitar falsos positivos. Una vez finalizado el evento, puedes reanudar el análisis de ARP/AI.



[[pause-arpai]]
== Pausa ARP/AI

Antes de iniciar un evento con una carga de trabajo inusual, es posible que tengas que suspender temporalmente el análisis ARP/AI para evitar falsos positivos.

.Pasos
. En System Manager, seleccione *Almacenamiento*.
. Seleccione las unidades de almacenamiento para las que desea pausar ARP/AI.
. Seleccione *Pausar anti-ransomware*.


.Resultado
El análisis de ARP/AI se pausa para las unidades de almacenamiento seleccionadas y no se le informa ninguna actividad sospechosa en el Administrador del sistema hasta que reanude ARP/AI.



[[resume-arpai]]
== Reanudar ARP/AI

Si detienes temporalmente ARP/AI durante una carga de trabajo inusual, reanúdala una vez finalizada dicha carga de trabajo para proteger tus datos frente a ataques de ransomware.

.Pasos
. En System Manager, seleccione *Almacenamiento*.
. Seleccione las unidades de almacenamiento para las que desea reanudar ARP/AI.
. Seleccione *Reanudar anti-ransomware*.


.Resultado
Se reanuda el análisis de posibles ataques de ransomware y se le informa sobre cualquier actividad sospechosa en el Administrador del sistema.
