---
sidebar: sidebar 
permalink: secure-data/respond-anti-ransomware-protection-alerts.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: Vea advertencias de posibles ataques de ransomware y tome medidas en el Administrador del sistema. 
---
= Responde a las alertas ARP/AI en los sistemas de almacenamiento ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la Protección autónoma contra el ransomware con inteligencia artificial (ARP/AI) detecta una actividad anómala en una o varias unidades de almacenamiento de tu sistema ASA r2, System Manager muestra una advertencia en el panel de control. Revisa la advertencia, verifica la actividad y actúa si es necesario para proteger tus datos.

Si aparece un mensaje de advertencia de ARP/AI, utiliza la herramienta de verificación de integridad de aplicaciones adecuada para comprobar los datos de la unidad de almacenamiento antes de tomar ninguna medida. Comprobar la integridad de los datos de la unidad de almacenamiento te ayuda a determinar si la actividad es aceptable o si se trata de un posible ataque de ransomware.

[cols="2,2"]
|===
| Si la actividad anormal es... | Entonces haz esto... 


| Aceptable | Marcar la actividad como falso positivo. 


| Un posible ataque de ransomware | Marcar la actividad como un posible ataque de ransomware. 


| Indeterminado | No tomes medidas inmediatas. Supervisa la unidad de almacenamiento durante un máximo de 7 días. Si la unidad de almacenamiento sigue funcionando con normalidad, marca la actividad como un falso positivo. Si la unidad de almacenamiento sigue mostrando una actividad anómala, marca la actividad como un posible ataque de ransomware. 
|===
.Pasos
. En System Manager, seleccione *Panel*.
+
Si ARP/AI ha detectado una actividad anómala en una o varias unidades de almacenamiento, aparece un mensaje en la sección *Advertencias*.

. Seleccione el mensaje de advertencia.
. En *Descripción general de eventos*, seleccione el mensaje *Advertencias* que indica la cantidad de unidades de almacenamiento con actividad anormal.
. En *Unidades de almacenamiento con actividad anormal*, seleccione la unidad de almacenamiento.
. Seleccione *Seguridad*.
+
Si hay actividad anormal en la unidad de almacenamiento, se muestra un mensaje debajo de *Anti-ransomware*.

. Seleccione *Elegir una acción*.
. Seleccione *Marcar como falso positivo* o seleccione *Marcar como posible ataque de ransomware*.


.El futuro
Si sabes de aumentos repentinos en la actividad de tu unidad de almacenamiento, ya sea un aumento puntual o uno que sea característico de una nueva normalidad, deberías reportarlos como seguros. Reportar manualmente estos picos como seguros ayuda a mejorar la precisión de las evaluaciones de amenazas de ARP. Descubre cómo link:https://docs.netapp.com/us-en/ontap/anti-ransomware/manage-parameters-task.html#report-known-surges["informar los aumentos de ARP/AI conocidos"^].
