---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features 
summary: Aunque los sistemas ASA R2 ofrecen una amplia gama de compatibilidad para las soluciones SAN, ciertas funciones de software ONTAP no son compatibles. 
---
= Compatibilidad del software ONTAP y limitaciones para los sistemas de almacenamiento R2 de ASA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas ASA r2 admiten una amplia gama de funcionalidades SAN, pero algunas funciones del software ONTAP no son compatibles.

.Los sistemas ASA R2 no son compatibles con lo siguiente:
* FabricPool
* Aprovisionamiento grueso de LUN
* MetroCluster
* Cifrado de agregados de NetApp (NAE)
* Protocolos de objetos
* ONTAP S3 SnapMirror y API S3
* SnapLock
+
SnapLock Compliance y Enterprise no son compatibles con los clústeres primarios en entornos SAN. SnapLock para SnapVault es compatible con los clústeres secundarios.

* La replicación SnapMirror es compatible con los sistemas ASA r2 con las siguientes limitaciones:
+
** La replicación síncrona de SnapMirror no es compatible.
** SnapMirror la replicación asíncrona solo es compatible entre dos sistemas ASA r2. SnapMirror la replicación asíncrona no es compatible entre un sistema ASA r2 y un sistema ASA, AFF o FAS, ni con la nube.
+
Obtenga más información sobrelink:../data-protection/pre-defined-protection-policies.html["Políticas de replicación de SnapMirror compatibles con sistemas ASA r2"] .

** La sincronización activa de SnapMirror solo es compatible entre dos sistemas ASA r2.
+
Obtenga más información sobrelink:../data-protection/snapmirror-active-sync.html["Sincronización activa de SnapMirror en sistemas ASA r2"] .





.Los sistemas ASA R2 ofrecen lo siguiente:
* Cifrado de doble capa
+
Los sistemas ASA r2 admiten el cifrado por hardware mediante unidades de cifrado automático (SED) y el cifrado por software mediante la tecnología NetApp Volume Encryption (NVE). link:../secure-data/encrypt-data-at-rest.html["Aprenda a aplicar el cifrado de doble capa"] a los datos en tu sistema ASA r2.



.Si quiere más información
* Consulte la link:https://hwu.netapp.com/["NetApp Hardware Universe"^] para obtener más información acerca de las limitaciones y la compatibilidad del hardware de ASA R2.

