---
sidebar: sidebar 
permalink: manage-data/storage-limits.html 
keywords: storage limits, cluster limits, maximum lun size, maximum, nodes per cluster, storage unit size, supported protocols, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30 
summary: Para un rendimiento, configuración y soporte óptimos, debe tener en cuenta los límites de almacenamiento de ASA r2. 
---
= Determina los límites de almacenamiento de tu sistema ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para un rendimiento, una configuración y un soporte óptimos, debes conocer los límites de almacenamiento de ASA r2.

Los límites pueden variar en función de tu sistema ASA r2 y de tu versión de ONTAP. Consulta link:https://hwu.netapp.com/["NetApp Hardware Universe"^] para ver una lista completa de los límites más recientes para tu sistema específico.


NOTE: Los límites de las máquinas virtuales (VM) no aparecen en Hardware Universe. El número máximo recomendado de máquinas virtuales por par de alta disponibilidad (HA) es de 800 y por clúster es de 1.200 según los límites de volumen del sistema ASA r2. Este límite no se aplica a las máquinas virtuales que residen en almacenes de datos VMFS. No existe un número máximo de máquinas virtuales para los almacenes de datos VMFS.

.Acerca de esta tarea
Los sistemas ASA r2 aparecen en NetApp Hardware Universe bajo *Products* como plataformas "ASA".

.Pasos
. Vaya a link:https://hwu.netapp.com["NetApp Hardware Universe"^].
. Selecciona *Productos*.
. En *Plataformas*, selecciona *ASA* como tu tipo de sistema.
. Selecciona tu sistema concreto y, a continuación, selecciona tu versión de ONTAP.
. Selecciona *Mostrar resultados*.


.Resultados
Se muestran los límites admitidos para tu sistema ASA r2 y tu versión de ONTAP concretos.
