---
sidebar: sidebar 
permalink: monitor/monitor-storage.html 
keywords: monitor, storage, cluster, utilization, usage 
summary: Supervise la utilización de su almacenamiento para asegurarse de que tiene la capacidad de almacenamiento que necesita para satisfacer las cargas de trabajo actuales y futuras. 
searchtitle: Supervise el uso del espacio con el administrador del sistema de ONTAP | ASA R2 
---
= Supervise el uso del clúster y de la unidad de almacenamiento en los sistemas de almacenamiento R2 de ASA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice System Manager de ONTAP para supervisar la utilización del almacenamiento y garantizar que dispone de la capacidad de almacenamiento necesaria para satisfacer las cargas de trabajo actuales y futuras.



[[monitor-cluster-utilization]]
== Supervise el uso del clúster

Supervise regularmente la cantidad de almacenamiento que consume el clúster para garantizar que, si es necesario, esté preparado para expandir la capacidad del clúster antes de quedarse sin espacio.

.Pasos
. En System Manager, seleccione *Panel*.
. En *Capacidad*, vea la cantidad de espacio físico utilizado y la cantidad de espacio disponible en su clúster.
+
La relación de reducción de datos representa la cantidad de espacio ahorrado gracias a la eficiencia del almacenamiento.



.El futuro
Si su clúster se está quedando sin espacio o si no tiene capacidad para satisfacer una demanda futura, debe planificar la link:../administer/increase-storage-capacity.html["añadir unidades nuevas"] puesta en marcha de su sistema ASA R2 para aumentar la capacidad de almacenamiento.



[[monitor-storage-availability-zone-utilization]]
== Supervise el uso de la zona de disponibilidad del almacenamiento

Cada par de HA de un sistema ASA r2 utiliza un pool de almacenamiento común denominado _zona de disponibilidad de almacenamiento_. La zona de disponibilidad de almacenamiento tiene acceso a todos los discos disponibles en el sistema de almacenamiento y es visible para ambos nodos del par de HA. La supervisión del espacio disponible de tus zonas de disponibilidad de almacenamiento te permite disminuir el uso o aumentar la capacidad según sea necesario para que no experimentes cargas de trabajo fallidas debido a un espacio insuficiente.

Si tiene 4 nodos o más en su clúster, puede ver la cantidad de espacio que utiliza la zona de disponibilidad de almacenamiento para cada par de alta disponibilidad. Esta métrica no está disponible para clústeres de 2 nodos.

A partir de ONTAP 9.19.1, se muestra una alerta en System Manager *Insights* si una zona de disponibilidad de almacenamiento en uno de los pares de HA del sistema ASA r2 se acerca a su capacidad. Más información sobre System Manager link:view-insights.html["Perspectivas"].

.Pasos
. En System Manager, seleccione *Cluster*; luego seleccione *Overview*.
+
Se muestra un resumen de la utilización de la zona de disponibilidad de almacenamiento de cada pareja de alta disponibilidad del clúster.

. Si desea obtener métricas más detalladas, seleccione una disponibilidad específica del almacenamiento.
+
En *Overview*, se muestra la capacidad de la zona de disponibilidad de almacenamiento, la cantidad de espacio utilizado y la relación de reducción de datos.

+
En *Unidades de almacenamiento*, se muestra una lista de todas las unidades de almacenamiento de la zona de disponibilidad de almacenamiento.



.El futuro
Si tu zona de disponibilidad de almacenamiento se está quedando sin espacio, deberías planear link:../manage-data/move-storage-units.html["mueva las unidades de almacenamiento"] a otra zona de disponibilidad de almacenamiento para equilibrar la utilización del almacenamiento en todo el clúster, eliminar snapshots para liberar espacio o agregar discos adicionales a tus nodos para aumentar la capacidad.



[[monitor-storage-unit-utilization]]
== Supervisar el uso de la unidad de almacenamiento

Supervisar la cantidad de almacenamiento consumido por una unidad de almacenamiento para aumentar de forma proactiva el tamaño de la unidad de almacenamiento en función de las necesidades de su negocio.

.Pasos
. En System Manager, seleccione *Almacenamiento*.
. Seleccione la unidad de almacenamiento que desea supervisar; luego seleccione *Descripción general*.
. En *Almacenamiento*, vea lo siguiente:
+
** Tamaño de la unidad de almacenamiento
** Cantidad de espacio utilizado
** De reducción de datos
+
La relación de reducción de datos representa la cantidad de espacio ahorrado gracias a la eficiencia del almacenamiento

** Instantánea utilizada
+
Snapshot utilizada representa la cantidad de almacenamiento que usan las instantáneas.





.El futuro
Si la unidad de almacenamiento se está acercando a su capacidad, debe link:../manage-data/modify-storage-units.html["modifique la unidad de almacenamiento"]aumentar su tamaño.
