---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, learn more, learn about, get started 
summary: 'Los sistemas ASA r2 (ASA A1K, A90, A70, A50, A30, A20, C30) ofrecen una solución unificada de hardware y software para una experiencia simplificada para los clientes que solo utilizan SAN.' 
searchtitle: Conozca los sistemas ASA A1K, A90, A70, A50, A30 A20 y C30 
---
= Obtenga información sobre los sistemas de almacenamiento R2 de ASA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas R2 de NetApp ASA ofrecen una solución de hardware y software unificada que crea una experiencia simplificada específica para las necesidades de los clientes de SAN exclusivamente.

Las siguientes plataformas de ASA se clasifican como sistemas ASA R2:

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30


Los sistemas ASA r2 admiten todos los protocolos SAN (iSCSI, FC, NVMe/FC, NVMe/TCP).  Los protocolos iSCSI, FC, NVMe/FC y NVMe/TCP admiten una arquitectura activa-activa simétrica para múltiples rutas, de modo que todas las rutas entre los hosts y el almacenamiento estén activas/optimizadas.  Los protocolos iSCSI y NVMe/TCP admiten la conexión directa entre los hosts y el almacenamiento.  Para los protocolos Fibre Channel y NVMe/FC no se admite la conexión directa.

En un sistema ASA R2, se han optimizado el software ONTAP y System Manager para proporcionar compatibilidad con las funciones SAN esenciales mientras se quitan características y funciones que no se admiten en los entornos SAN.

Los sistemas R2 de ASA introducen el uso de unidades de almacenamiento con grupos de coherencia:

* A _storage unit_ hace que el espacio de almacenamiento esté disponible para los hosts SAN para realizar operaciones de datos. Una unidad de almacenamiento hace referencia a un LUN para hosts SCSI o un espacio de nombres NVMe para los hosts NVMe.
* _Un grupo de consistencia_ es una colección de unidades de almacenamiento que se gestionan como una sola unidad.


Los sistemas ASA r2 utilizan unidades de almacenamiento con grupos de consistencia para simplificar la administración del almacenamiento y la protección de datos.  Por ejemplo, supongamos que tiene una base de datos que consta de 10 unidades de almacenamiento en un grupo de consistencia y necesita realizar una copia de seguridad de toda la base de datos.  En lugar de realizar una copia de seguridad de cada unidad de almacenamiento individualmente, puede proteger toda la base de datos realizando una copia de seguridad del grupo de consistencia.

Para proteger sus datos contra ataques maliciosos, como robo o ransomware, los sistemas ASA r2 incorporan un administrador de claves, cifrado de doble capa, autenticación multifactor y verificación multiadministrador. Los sistemas ASA r2 secundarios también admiten instantáneas a prueba de manipulaciones.

Los sistemas ASA r2 no admiten la combinación de clústeres con sistemas ASA, AFF o FAS .

.Si quiere más información
* Obtenga más información sobre la compatibilidad con los sistemas ASA R2 y las limitaciones en la link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Más información sobre link:../learn-more/hardware-comparison.html["Los sistemas ASA R2 en comparación con los sistemas ASA"].
* Obtenga más información sobre el link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA de NetApp"].

