---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, learn more, learn about, get started 
summary: 'Los sistemas R2 de ASA (ASA A1K, A90, A70) ofrecen una solución unificada de hardware y software para una experiencia simplificada para clientes solo de SAN.' 
searchtitle: Obtenga información sobre los sistemas A1K, A90 y A70 de ASA 
---
= Obtenga información sobre los sistemas de almacenamiento R2 de ASA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas NetApp ASA R2 (ASA A1K, ASA A70 y ASA A90) ofrecen una solución de hardware y software unificada que crea una experiencia simplificada específica de las necesidades de clientes exclusivos de SAN.

Los sistemas R2 de ASA son compatibles con todos los protocolos SAN (iSCSI, FC, NVMe/FC, NVMe/TCP). Los protocolos iSCSI, FC, NVMe/FC y NVMe/TCP admiten una arquitectura activo-activo simétrica para la multivía, de modo que todas las rutas entre los hosts y el almacenamiento estén activas/optimizadas. Los protocolos iSCSI y NVMe/TCP admiten rutas directas entre los hosts y el almacenamiento.

En un sistema ASA R2, se han optimizado el software ONTAP y System Manager para proporcionar compatibilidad con las funciones SAN esenciales mientras se quitan características y funciones que no se admiten en los entornos SAN.

Los sistemas R2 de ASA introducen el uso de unidades de almacenamiento con grupos de coherencia:

* A _storage unit_ hace que el espacio de almacenamiento esté disponible para los hosts SAN para realizar operaciones de datos. Una unidad de almacenamiento hace referencia a un LUN para hosts SCSI o un espacio de nombres NVMe para los hosts NVMe.
* _Un grupo de consistencia_ es una colección de unidades de almacenamiento que se gestionan como una sola unidad.


Los sistemas R2 de ASA utilizan unidades de almacenamiento y grupos de consistencia para simplificar la administración del almacenamiento y la protección de datos. Por ejemplo, suponga que tiene una base de datos que consta de 10 unidades de almacenamiento en un grupo de coherencia y necesita realizar un backup de toda la base de datos. En lugar de realizar un backup de cada unidad de almacenamiento de forma individual, puede proteger toda la base de datos mediante un backup del grupo de coherencia.

Para ayudar a proteger sus datos contra ataques maliciosos como el robo o ransomware, los sistemas ASA R2 admiten un administrador de claves integrado, cifrado de doble capa, copias Snapshot a prueba de manipulaciones, autenticación multifactor y verificación multiadministrador.

Los sistemas R2 de ASA no admiten la combinación de clústeres con los sistemas ASA, AFF o FAS actuales.

.Si quiere más información
* Obtenga más información sobre la compatibilidad con los sistemas ASA R2 y las limitaciones en la link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Más información sobre link:../learn-more/hardware-comparison.html["Los sistemas ASA R2 en comparación con los sistemas ASA"].
* Obtenga más información sobre el link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA de NetApp"].

