---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, learn more, learn about, get started 
summary: 'Los sistemas ASA r2 (ASA A1K, A90, A70, A50, A30, A20, C30) ofrecen una solución unificada de hardware y software para una experiencia simplificada para los clientes que solo utilizan SAN.' 
searchtitle: Conozca los sistemas ASA A1K, A90, A70, A50, A30 A20 y C30 
---
= Obtenga información sobre los sistemas de almacenamiento R2 de ASA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los sistemas ASA r2 de NetApp ofrecen una solución unificada de hardware y software que crea una experiencia simplificada específica para las necesidades de los clientes solo SAN. En un sistema ASA r2, el software ONTAP y System Manager están optimizados para proporcionar soporte para la funcionalidad esencial de SAN, eliminando funciones y características que no son compatibles en entornos SAN.

Los siguientes sistemas se clasifican como sistemas ASA r2:

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30


.Unidades de almacenamiento y grupos de consistencia
Los sistemas R2 de ASA introducen el uso de unidades de almacenamiento con grupos de coherencia:

* A _storage unit_ hace que el espacio de almacenamiento esté disponible para los hosts SAN para realizar operaciones de datos. Una unidad de almacenamiento hace referencia a un LUN para hosts SCSI o un espacio de nombres NVMe para los hosts NVMe.
* _Un grupo de consistencia_ es una colección de unidades de almacenamiento que se gestionan como una sola unidad.


Los sistemas ASA r2 utilizan unidades de almacenamiento con grupos de consistencia para simplificar la administración del almacenamiento y la protección de datos.  Por ejemplo, supongamos que tiene una base de datos que consta de 10 unidades de almacenamiento en un grupo de consistencia y necesita realizar una copia de seguridad de toda la base de datos.  En lugar de realizar una copia de seguridad de cada unidad de almacenamiento individualmente, puede proteger toda la base de datos realizando una copia de seguridad del grupo de consistencia.

.Protección y seguridad de los datos
Para ayudarte a proteger tus datos frente a ataques maliciosos como el robo o el ransomware, los sistemas ASA r2 incorporan un gestor de claves integrado, cifrado de doble capa, autenticación multifactor y verificación de múltiples administradores. También puedes replicar instantáneas en una ubicación secundaria y usar SnapLock para SnapVault para proteger las instantáneas de destino y evitar que se eliminen accidental o maliciosamente.

.Protocolos compatibles, multivía y configuraciones
Los sistemas ASA r2 son compatibles con todos los protocolos SAN (iSCSI, FC, NVMe/FC, NVMe/TCP). Todos los protocolos admiten una arquitectura simétrica activa-activa para el multipathing, así que todos los caminos entre los hosts y el almacenamiento están activos y optimizados. Los protocolos iSCSI y NVMe/TCP admiten configuraciones de red y de conexión directa para todas las versiones de ONTAP compatibles. Los protocolos FC y NVMe/FC admiten configuraciones de red para todas las versiones compatibles de ONTAP y, a partir de ONTAP 9.19.1, también admiten la configuración de conexión directa. Los sistemas ASA r2 no admiten la combinación de clústeres con sistemas ASA, AFF o FAS.

* Más información sobre link:https://docs.netapp.com/us-en/ontap/san-admin/multipath-automatic-lif-failover-support.html["Compatibilidad con multivía en SAN"^].
* Más información sobre link:https://docs.netapp.com/us-en/ontap/san-config/configure-iscsi-san-hosts-ha-pairs-reference.html["Configuraciones para los protocolos iSCSI y NVMe/TCP"^].
* Más información sobre link:https://docs.netapp.com/us-en/ontap/san-config/configure-fc-nvme-hosts-ha-pairs-reference.html["Configuraciones para los protocolos FC y NVMe/FC"^].


.Información relacionada
* Obtenga más información sobre la compatibilidad con los sistemas ASA R2 y las limitaciones en la link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Más información sobre link:../learn-more/hardware-comparison.html["Los sistemas ASA R2 en comparación con los sistemas ASA"].
* Obtenga más información sobre el link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA de NetApp"^].

