---
sidebar: sidebar 
permalink: data-protection/manage-consistency-groups.html 
keywords: consistency groups, snapshots, data protection, protect data, add, remove, delete, storage units, lun, namespace, increase capacity 
summary: Use grupos de coherencia para realizar varias acciones a varias unidades de almacenamiento al mismo tiempo en lugar de realizar acciones individualmente en cada unidad. 
---
= Obtenga información sobre los grupos de consistencia de ONTAP en los sistemas de almacenamiento ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un grupo de consistencia es una colección de unidades de almacenamiento que se administran como una sola unidad.  Utilice grupos de consistencia para una gestión simplificada del almacenamiento.

Por ejemplo, supongamos que tiene una base de datos que consta de 10 unidades de almacenamiento en un grupo de consistencia y necesita realizar una copia de seguridad de toda la base de datos. En lugar de realizar una copia de seguridad de cada unidad de almacenamiento, puede realizar una copia de seguridad de toda la base de datos simplemente agregando protección de datos de instantáneas al grupo de consistencia.  Realizar una copia de seguridad de las unidades de almacenamiento como un grupo de consistencia en lugar de hacerlo individualmente también proporciona una copia de seguridad consistente de todas las unidades, mientras que realizar una copia de seguridad de las unidades individualmente podría crear potencialmente inconsistencias.

A partir de ONTAP 9.16.1, puede usar el Administrador del sistema para crear grupos de consistencia jerárquicos en su sistema ASA r2.  En una estructura jerárquica, uno o más grupos de consistencia se configuran como hijos de un grupo de consistencia padre.

Los grupos de coherencia jerárquicos le permiten aplicar políticas Snapshot individuales a cada grupo de coherencia secundario y replicar las snapshots de todos los grupos de coherencia secundarios en un clúster remoto como una sola unidad mediante la replicación del elemento primario. De esta forma se simplifica la protección y la gestión de datos para estructuras de datos complejas. Por ejemplo, suponga que crea un grupo de consistencia primario llamado `SVM1_app` que contiene dos grupos de consistencia secundarios: `SVM1app_data` Para los datos de la aplicación y `SVM1app_logs` para los registros de la aplicación. Se realizan Snapshots de `SVM1app_data` cada 15 minutos y se realizan Snapshots de `SVM1app_logs` cada hora. El grupo de coherencia primario `SVM1_app,` tiene una política SnapMirror que replica las copias Snapshot de `SVM1app_data` tanto como `SVM1app_logs` en un clúster remoto cada 24 horas. El grupo de coherencia primario `SVM1_app` se administra como una unidad única y los grupos de coherencia secundarios se gestionan como unidades independientes.



== Grupos de consistencia en relaciones de replicación

A partir de ONTAP 9.17.1, puede realizar los siguientes cambios de geometría en los grupos de consistencia en una relación de replicación asincrónica o en una relación de sincronización activa de SnapMirror sin interrumpir ni eliminar la relación.  Cuando se produce un cambio de geometría en el grupo de consistencia principal, el cambio se replica en el grupo de consistencia secundario.

* link:manage-consistency-groups-add-remove-storage-units.html["Modificar el tamaño de una unidad de almacenamiento"]añadiendo o quitando unidades de almacenamiento.
* link:manage-hierarchical-consistency-groups.html#promote-an-existing-consistency-group-into-a-parent-consistency-group["Promover un único grupo de consistencia"]a un grupo de consistencia padre.
* link:manage-hierarchical-consistency-groups.html#demote-a-parent-consistency-group-to-a-single-consistency-group["Degradar un grupo de consistencia principal"]a un solo grupo de consistencia.
* link:manage-hierarchical-consistency-groups.html#detach-a-child-consistency-group-from-a-parent-consistency-group["Separar un grupo de consistencia secundario"]de un grupo de consistencia padre.
* link:manage-hierarchical-consistency-groups.html#create-a-child-consistency-group["Cree un grupo de consistencia secundario"]utilizando un grupo de consistencia existente.


En ONTAP 9.16.1, debelink:snapmirror-active-sync-break-relationship.html["romper la relación de replicación asincrónica"] ylink:snapmirror-active-sync-delete-relationship.html["eliminar la relación de sincronización activa de SnapMirror"] antes de realizar cambios de geometría en el grupo de consistencia.
