---
sidebar: sidebar 
permalink: release-notes/changes-to-limits-defaults.html 
keywords: release notes, changes, updates, defaults, limits, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30 
summary: Obtenga más información sobre los cambios en los límites y valores predeterminados que afectan a los sistemas ASA R2. 
---
= Cambios en los límites y valores predeterminados de ONTAP que afectan a los sistemas ASA R2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Obtenga más información sobre los cambios en los límites y valores predeterminados que afectan a los sistemas ASA R2. NetApp se esfuerza por ayudar a sus clientes a comprender los cambios de límite y predeterminados más importantes en cada versión de ONTAP.



== Cambios en los límites de ONTAP

[cols="2,4,4"]
|===
| Función | Cambio de límite | Cambiado en la versión... 


| Máquinas virtuales de almacenamiento por clúster | El número máximo de máquinas virtuales (VM) de almacenamiento admitidas por par HA se incrementa de 32 a 256. | ONTAP 9.18.1 


| Sincronización activa de SnapMirror | Se amplía la compatibilidad con la sincronización activa de SnapMirror de clústeres de dos nodos a clústeres de cuatro nodos. | ONTAP 9.18.1 


| Nodos por clúster  a| 
El número máximo de nodos por clúster ha aumentado de 2 a 12.


NOTE: Si ejecuta ONTAP 9.16.1 con más de 2 nodos en un clúster, no puede revertir a ONTAP 9.16.0.
| ONTAP 9.16.1 


| Unidades de almacenamiento | El número máximo de unidades de almacenamiento ha aumentado de 2500 TB por par de alta disponibilidad a 10.000 TB por par de alta disponibilidad. | ONTAP 9.16.1 
|===